// Story Generator Tables — extracted from docs/story_generator_tables.md
// Used by randomizeNarrativeBrief() to compose random narrative briefs.
// Each array is a d100 or d20 table. Index 0 = roll 1.

window.STORY_TABLES = {

genreTone: [
"Dustbowl literary realism — hardship, dignity, the land as antagonist",
"Southern Gothic — decay, family secrets, grotesque beauty, complicit grace",
"Noir — moral ambiguity, rain-slicked streets, everyone is compromised",
"Hard-boiled crime — cynical protagonist, corrupt institutions, violence as punctuation",
"Psychological thriller — unreliable perception, paranoia, identity erosion",
"Gothic horror — inheritance, dread, ancestral sin made manifest",
"Cosmic horror — humanity is irrelevant, knowledge destroys, nothing is safe",
"Folk horror — rural community, old rites, the land remembers",
"Body horror — transformation, violation of self, flesh as betrayal",
"Quiet horror — dread without monsters, the unbearable in the mundane",
"Domestic drama — kitchen-sink realism, love and resentment in close quarters",
"Kitchen-sink tragedy — working class, systemic failure, individual dignity",
"Political drama — institutions versus conscience, power\u2019s corrupting logic",
"Spy thriller — Cold War logic, loyalty as illusion, tradecraft and betrayal",
"Espionage literary — Le Carr\u00e9 tone, moral exhaustion, the cost of the grey world",
"War drama — combat as crucible, the things carried, survival versus humanity",
"Anti-war satire — absurdism as protest, heroism debunked, institutions as farce",
"Western frontier — lawlessness, myth-making, violence and its consequence",
"Revisionist western — subverted mythology, forgotten voices, empire\u2019s edge",
"Post-apocalyptic survival — resource scarcity, community formation, moral drift",
"Post-apocalyptic literary — loss as elegy, what remains of the human, grief as landscape",
"Epic fantasy — heroic destiny, world-historical stakes, myth in motion",
"Grimdark fantasy — power is corruption, heroism is propaganda, mud and consequence",
"Low fantasy — magic is rare and strange, history is the antagonist, grit",
"Mythological — gods walk, fate is real, hubris is a law of nature",
"Folkloric — oral tradition logic, tricksters, bargains, the forest as moral space",
"Fairy tale dark — wish fulfillment turned terrible, transformation as violence",
"Magical realism — the impossible is mundane, emotion made literal",
"Surrealist — dream logic, bureaucracy as nightmare, meaning in the unreasonable",
"Absurdist — Camus or Kafka tone, systems without purpose, dignity in futility",
"Hard science fiction — physics as character, humanity vs. environment, ideas as plot",
"Social science fiction — technology as social critique, power structures extrapolated",
"Biopunk — biological manipulation, identity and genome, life commodified",
"Cyberpunk — corporate hegemony, street-level resistance, technology and alienation",
"Solarpunk — cooperation, sustainability, hope as radical act",
"Space opera — grand scale, political intrigue among stars, found family",
"New Weird — genre blended, cities as organisms, ideology made physical",
"Weird West — supernatural frontier, colonialism and consequence, myth made monstrous",
"Lovecraftian mythos — specific pantheon, fragile sanity, ancient malevolence",
"Contemporary conspiracy — paranoia, government shadows, forbidden knowledge",
"Historical fiction — period texture, known events as backdrop, human scale",
"Ancient world — empire and republic, honor codes, gods in politics",
"Medieval — feudal logic, crusade and plague, faith as power",
"Renaissance intrigue — patronage, poison, art as politics",
"Age of Sail — empire and piracy, the ocean as void, trade and exploitation",
"Victorian — class anxiety, empire\u2019s guilt, science versus superstition",
"Edwardian twilight — the last innocence before catastrophe, doomed elegance",
"1920s — jazz and horror underneath, prohibition logic, the modern arriving violently",
"1930s — depression and fascism rising, collective despair, idealism tested",
"1940s — total war, sacrifice, the home front, what is worth dying for",
"1950s — conformity as suffocation, the bomb under everything, suburbia as cage",
"1960s — fracture and possibility, counterculture, assassination and idealism",
"1970s — paranoia justified, systems collapsing, cynicism earned",
"1980s — excess and hollowness, Cold War endgame, neon over despair",
"Contemporary realism — now, the fraying present, no clean answers",
"Near future — 20 years out, trends followed to conclusion, recognizable and wrong",
"Far future — civilization cycles, the long view, humanity as memory",
"Coming of age — identity formation under pressure, initiation, the loss of innocence",
"Campus/academic — ideas have consequences, institutional rot, minds in formation",
"Road narrative — movement as escape and pursuit, the country as mirror",
"Ocean/maritime — isolation, the deep, communities of survival",
"Arctic/extreme environment — endurance, stripped identity, the sublime as threat",
"Jungle/wilderness — civilization\u2019s edge, the animal beneath, what survives",
"Urban literary — city as ecosystem, anonymity and community, poverty and proximity",
"Small town — everyone knows, the past won\u2019t die, secrets in plain sight",
"Immigrant experience — two worlds, identity negotiation, belonging as labor",
"Diaspora narrative — cultural inheritance, generational rupture, home as myth",
"Prison narrative — constrained freedom, power microcosm, time as punishment",
"Medical drama — mortality as constant, institutional ethics, the body\u2019s betrayal",
"Legal thriller — truth versus justice, rhetoric as power, guilt and proof",
"Financial thriller — systems that eat people, greed as ideology, complicity",
"Heist/caper — competence as pleasure, the ensemble, the elegant plan unraveling",
"Revenge tragedy — justice and obsession, the cost of righting wrongs",
"Romance (literary) — emotional truth, vulnerability as courage, love as change",
"Romance (dark) — desire and danger, power asymmetry, the edge",
"Queer narrative — identity under pressure, chosen family, visibility as survival",
"Disability narrative — the world built wrong, accommodation as resistance",
"Addiction narrative — self-destruction as logic, the wanting mind, bottom and return",
"Grief narrative — the shape of loss, time distorted, what remains",
"Trauma narrative — the past in the present, the body\u2019s memory, healing\u2019s ambiguity",
"Religious/faith narrative — belief under pressure, doubt as honesty",
"Cult narrative — seduction of belonging, ideology as trap, the exit",
"Occult thriller — hidden knowledge, genuine danger, the price of seeing",
"Paranormal investigation — the threshold between rational and not, dread building slowly",
"Vampire — power, seduction, predation, society\u2019s shadow",
"Werewolf/shapeshifter — identity split, the beast within, cycles",
"Ghost story — unfinished business, the past refusing to release, grief made visible",
"Apocalyptic religious — prophecy, rapture logic, the chosen few, terror and ecstasy",
"Eco-horror — nature as avenger, the cost of exploitation, the food chain reversed",
"Techno-thriller — systems weaponized, infrastructure as battlefield",
"Pandemic/plague — contagion logic, social collapse by degrees, who gets to live",
"Disaster narrative — event as crucible, community under pressure, heroism without glory",
"Heist gone wrong — competence fails, improvisation, everyone\u2019s true nature exposed",
"Generational saga — decades, inheritance, patterns repeating across blood",
"Epistolary — documents and letters, unreliable narrators, what\u2019s left out",
"Fairy tale realism — the logic of stories applied literally to a real world",
"Slipstream — neither genre nor literary, the uncomfortable in-between",
"Cli-fi — climate change as protagonist, slow catastrophe, complicity",
"Afrofuturism — cultural inheritance forward-projected, liberation and speculation"
],

setting: [
"A dying agricultural town during economic collapse",
"A river delta community built on migration and flood",
"A massive industrial city during a labor movement",
"A port city where four cultures uneasily coexist",
"A coastal fishing village slowly losing its reason for existing",
"A sprawling plantation in its twilight years",
"A small Southern town where nothing is forgotten",
"A migrant labor camp following the harvest",
"A border town — legally, culturally, temporally ambiguous",
"A mountain community cut off by winter",
"A desert town built around a single dying resource",
"An island whose only industry is a single product or estate",
"A university town where the institution dominates everything",
"A military base in a foreign country",
"A hospital — contained, hierarchical, life and death as daily rhythm",
"A prison — maximum security, during a specific inciting event",
"A courthouse during a landmark trial",
"A psychiatric institution — the line between help and harm blurred",
"A wealthy estate during its owner\u2019s final years",
"A crumbling manor with a history too heavy to escape",
"A city under occupation by a foreign power",
"A city in the final days before a known catastrophe",
"An underground bunker — self-contained society, claustrophobic politics",
"A submarine on a long, isolated mission",
"A research station in an extreme environment",
"A space station — the last one, the first one, or the forgotten one",
"A generation ship mid-voyage with no living memory of origin",
"A colony on a planet not yet ready for humans",
"A space station orbiting a phenomenon no one understands",
"A derelict vessel drifting — with something still aboard",
"An ancient city in political transition",
"A medieval castle during siege or succession crisis",
"A trade city at the crossroads of three empires",
"A temple complex — religious, political, and dangerous",
"A ship crossing an ocean with a dangerous cargo or passenger",
"A frontier fort — the edge of official civilization",
"A gold rush town building itself too fast to have ethics yet",
"A train — contained, moving, hierarchical, no exit",
"A traveling circus or carnival",
"A hotel that functions as a world unto itself",
"A city whose streets literally change",
"A forest that remembers older things",
"An underwater city or habitat",
"A library that contains more than books",
"A city built inside a massive structure",
"A refugee camp in a conflict zone",
"A post-collapse city with a functioning community inside its ruins",
"A massive corporate campus that functions as a city",
"A favela or informal settlement with its own governance",
"A suburb during a slow emergency no one officially acknowledges",
"A neighborhood in rapid gentrification — old world and new in collision",
"A small nation between two larger powers",
"A government intelligence agency during a period of crisis",
"A newsroom covering a story that may destroy the publication",
"A law firm during a case that will define careers and ruin lives",
"A laboratory on the edge of a discovery that changes everything",
"A megachurch — faith, money, politics, charisma",
"A monastery or convent — sequestered, but the world intrudes",
"An archaeological dig that uncovers something that should have stayed buried",
"A museum — curated history, institutional power, hidden provenance",
"A theater or opera house during a critical season",
"A recording studio during the making of a legendary album",
"A film set — illusion and labor, art and commerce at war",
"An auction house handling a collection of mysterious objects",
"A private school with generations of legacy and buried incidents",
"A village recently emerged from authoritarian rule",
"A city in the grip of a not-quite-explicable plague",
"A region under surveillance — every surface watched",
"A decaying amusement park or fairground",
"A river journey through increasingly strange territory",
"A bayou community — time moves differently, memory is water",
"A city of canals in decline — beauty and rot, the smell of history",
"A walled city during a siege that has lasted years",
"A mountain monastery above the clouds — isolated, ancient, disturbed",
"A commune or utopian community in its third decade",
"A cruise ship — luxury as microcosm, class and leisure, the sea below",
"A research university during a decade of campus upheaval",
"A small town where everyone quietly knows about something monstrous",
"The halls of government during a constitutional crisis",
"A city during a heat wave — tempers, death, the body\u2019s limit",
"A district during a power outage that lasts long enough to change behavior",
"A wildfire evacuation zone — loss, decision, who stays",
"A flooded city — half above water, half below, new social strata",
"An ancient forest being cleared — the last section, the last defenders",
"A neighborhood dominated by a single employer who is now leaving",
"A city with two justice systems — one official, one older",
"A marketplace at the edge of multiple hostile territories",
"A network of tunnels beneath a city — people live there",
"A sky city — built on elevated infrastructure, ground is memory",
"A nation-state that exists only digitally, with physical enclaves",
"A game reserve or nature preserve — wildlife, trespass, surveillance",
"A vineyard or farm — seasonal rhythm, land as inheritance, labor",
"A hospital ship during wartime",
"A diplomatic mission in a country on the verge of revolution",
"A black site — officially nonexistent, very real",
"A pocket reality — a space that operates by different rules",
"A city that exists in multiple time periods simultaneously",
"A space between places — a way station, a limbo, a waiting room",
"A setting that is the interior of a mind, a memory, or a dream"
],

protagonist: [
"The migrant — displaced, carrying home inside, looking for ground",
"The returnee — left, changed elsewhere, now back where they don\u2019t fit",
"The survivor — has already been through the worst, now must live after",
"The witness — present at events, complicit by observation, burdened by seeing",
"The keeper — maintaining something at great cost",
"The idealist — believes the system can work, is about to be tested",
"The former idealist — was burned once, has rebuilt a careful cynicism",
"The pragmatist — morality is situational, survival is the argument",
"The true believer — ideology fills the space where doubt should live",
"The apostate — escaped a belief system, carries it like a scar",
"The detective — pattern recognition as compulsion, truth as vocation",
"The investigator who shouldn\u2019t be investigating — amateur, obsessed",
"The fixer — makes problems disappear, accumulating debts",
"The enforcer — does the violence for people who prefer clean hands",
"The informant — living between two worlds, belonging to neither",
"The double agent — loyalty as performance, truth as death",
"The scientist — observation before emotion, but the emotion is there",
"The whistleblower — decided to speak, the machine is now turning",
"The archivist — the past as vocation, history as dangerous",
"The translator — between languages, cultures, worlds, always in-between",
"The journalist — seeking truth in a world that prefers narrative",
"The soldier who stopped believing — trained for violence, no longer certain why",
"The veteran — carries the war internally, civilian world feels thin",
"The refugee — fleeing, not arrived, the journey is the story",
"The aristocrat in decline — inheriting a world already gone",
"The laborer — dignity as resistance, the body as means of production",
"The artist — making meaning in a world hostile to meaning",
"The con artist — performing identity, truth as variable",
"The smuggler — moving things across lines the powerful drew",
"The revolutionary — the world must change, the cost is acceptable",
"The priest or spiritual leader — faith as vocation, the doubt they hide",
"The prophet — believes they see truly, may or may not be right",
"The healer — traditional or institutional, the body as moral field",
"The farmer — connected to land and cycle, at the mercy of systems",
"The hunter — tracker, alone in the wild, predator who thinks about it",
"The elder — the end of their generation, the weight of having seen",
"The child navigating an adult world — too much, too young",
"The middle-aged person in crisis — the life built is not the life wanted",
"The orphan — unmade by loss, rebuilding identity from scratch",
"The outsider — observes the community without belonging, reveals it to us",
"The newcomer — sees what locals can\u2019t anymore, endangers the settled",
"The local who knows too much — has always known, chose silence",
"The addict — the want is louder than everything else",
"The person hiding their condition — the performance of normality",
"The person who survived something no one will believe",
"The person who saw something they were not supposed to see",
"The cryptographer or code-breaker — meaning hidden in everything",
"The curator or collector — obsessed with objects, meaning in things",
"The explorer — the edge of the known, the self stripped to essential",
"The engineer of terrible things — made something, must face what it does",
"The hacker — systems as landscape, information as weapon and wound",
"The functionally inhuman — AI, android, vampire — wearing personhood",
"The person slowly becoming something else — transformation as horror or gift",
"The last of something — the final speaker, the final practitioner",
"The person who has seen the worst truth about reality — and must keep functioning",
"The ordinary person — no special qualification except necessity"
],

want: [
"To find a missing person",
"To expose the truth",
"To survive",
"To protect someone they love",
"To belong somewhere",
"To go home",
"To leave home forever",
"To be recognized for who they truly are",
"To understand what happened to them",
"To complete the work someone left unfinished",
"To stop the thing before it\u2019s too late",
"To find out what they truly are",
"To destroy something that has destroyed others",
"To build something that lasts",
"To escape an obligation",
"To keep a secret from ever coming out",
"To find peace",
"To feel something again",
"To be believed",
"To save an institution they believe in",
"To bring someone to justice",
"To get out before it collapses",
"To hold the community together",
"To discover the truth about their origin",
"To protect the secret, even if it destroys them",
"To complete the mission, whatever the cost",
"To understand the phenomenon, the mystery, the anomaly",
"To acquire an object of power or meaning",
"To get the confession",
"To maintain the lie one more day",
"To document something before it vanishes",
"To master a craft or discipline",
"To stop the bleeding \u2014 literal or metaphorical",
"To reach a person who has retreated beyond reach",
"To find the lie in the story everyone believes",
"To make the powerful answer for what they\u2019ve done",
"To understand the thing that is coming",
"To hold on to themselves while everything tries to change them",
"To undo something they set in motion",
"To stop something from being forgotten",
"To make something beautiful before the end"
],

antagonist: [
"A specific person \u2014 former ally who believes the protagonist betrayed them first",
"A specific person \u2014 a mirror of what the protagonist could become",
"A specific person \u2014 someone doing wrong for right reasons",
"A specific person \u2014 survivor of the protagonist\u2019s choices, the past catching up",
"An institution \u2014 government agency prioritizing institutional survival over truth",
"An institution \u2014 corporation, profit over people, invisibly",
"An institution \u2014 religious organization, dogma over humanity in good faith",
"An institution \u2014 the family as structure requiring performance over truth",
"A system \u2014 bureaucracy, process as obstruction without intent",
"A system \u2014 surveillance state, watching as control",
"Nature \u2014 a disease, indifferent, systematic, without hatred",
"Nature \u2014 the environment the protagonist must traverse",
"Nature \u2014 the body\u2019s own limits, illness, aging",
"The supernatural \u2014 a curse, mechanism of old harm still operating",
"The supernatural \u2014 an eldritch entity, no motivation legible to human minds",
"The cosmic \u2014 the universe\u2019s indifference, nothing is watching",
"The cosmic \u2014 an ancient intelligence, existed before humanity",
"The self \u2014 addiction, the wanting part against the rest",
"The self \u2014 trauma response, survival mechanism that is now the danger",
"The self \u2014 the protagonist\u2019s need for control",
"Time \u2014 the deadline, running out before completion",
"Time \u2014 the accumulated past, history\u2019s weight on the present",
"Information \u2014 what cannot be un-known, knowledge itself as antagonist",
"Information \u2014 the lie everyone believes, false consensus as force",
"A faction \u2014 two factions and the protagonist between them, both partly right",
"A conspiracy \u2014 distributed, emergent, no one at the center",
"A technology \u2014 autonomous, indifferent, doing what it was designed to do",
"An idea \u2014 a meme, an ideology, spreading and changing people",
"Necessity \u2014 there is no villain, everyone is doing what they must",
"The antagonist is the protagonist from a different angle \u2014 same story, different role",
"There is no antagonist \u2014 the conflict is entirely internal"
],

theme: [
"Can a person outrun who they were?",
"What do we owe the people who made us?",
"Is loyalty a virtue or a trap?",
"What does justice actually require?",
"Can love survive the truth?",
"When does survival become complicity?",
"Is honesty a gift or a weapon?",
"What makes a life meaningful?",
"What do we become when we fight monsters?",
"Does the past determine the present?",
"Can people change, or only circumstances?",
"What do we owe strangers?",
"Is hope rational?",
"Can violence be moral?",
"What is left when faith fails?",
"Who decides what is true?",
"What does it mean to belong?",
"What is the cost of silence?",
"Who are we when no one is watching?",
"Is freedom possible within systems?",
"What is the relationship between memory and identity?",
"What do we owe those who come after us?",
"Can beauty survive in conditions of cruelty?",
"Who gets to be human?",
"What happens to identity under pressure?",
"Does knowing make things better or worse?",
"Is the self coherent? Or is it many, and in conflict?",
"What is dignity, and can it be stripped?",
"Can empathy cross fundamental difference?",
"What is the cost of certainty?",
"Is the world comprehensible? Or is that a story we tell?",
"What is the relationship between grief and love?",
"Can the damaged be healed?",
"Is history progress or cycle?",
"What does civilization protect, and what does it destroy?",
"Can art save anyone?",
"What is the relationship between the body and the self?",
"Is revenge ever sufficient?",
"What do we owe our enemies?",
"Can a broken person build something whole?",
"Is there such a thing as fate?",
"What is the nature of sacrifice?",
"What remains when everything is taken?",
"Is goodness a condition or a choice?",
"Can meaning be found \u2014 or only made?",
"What do we owe those we have hurt?",
"What is worth dying for? What is worth living for? Are they the same?",
"What is the cost of truth when the world prefers the lie?"
],

touchstone: [
"Roadside Picnic \u2014 alien contact as environmental disaster, the human scrambling beneath the incomprehensible",
"Gormenghast \u2014 institution as organism, ritual suffocating the living, atmosphere over plot",
"The Haunting of Hill House \u2014 the house as psychological projection, interiority as the real horror",
"We Have Always Lived in the Castle \u2014 unreliable narrator who is right about everything",
"Blood Meridian \u2014 violence as cosmic force, the frontier as moral void",
"Blindsight \u2014 consciousness as evolutionary accident, first contact as annihilation of anthropocentrism",
"The Book of the New Sun \u2014 unreliable narrator who is also the hero, far future as mythologized past",
"The Left Hand of Darkness \u2014 gender and cold and politics, the outsider as lens",
"Parable of the Sower \u2014 near-future collapse, community as survival technology, the prophet as pragmatist",
"The Spy Who Came In From the Cold \u2014 the moral cost of the grey world, being used without consent",
"Tinker Tailor Soldier Spy \u2014 patience as method, the mole hunt as meditation on trust",
"House of Leaves \u2014 the document as horror, the house larger inside than outside",
"True Grit \u2014 the narrator\u2019s voice as unreliable moral authority, competence and grief",
"The Things They Carried \u2014 the story about the story as the story, war truth versus war fact",
"Beloved \u2014 the haunting as historical reckoning, the body\u2019s memory, love as the most violent force",
"The Wind-Up Bird Chronicle \u2014 ordinary surface hiding an abyss, the domestic invaded by history",
"Never Let Me Go \u2014 what we don\u2019t ask about, complicit acceptance, horror in restraint and politeness",
"The Remains of the Day \u2014 the life wasted in service, dignity as self-deception",
"Annihilation \u2014 the unreliable expedition narrator, ecological horror, identity dissolving",
"Piranesi \u2014 innocence inside the inexplicable, the captive who doesn\u2019t know, memory as the actual story",
"The City & The City \u2014 law as unreality, the divided city as cognitive dissonance",
"The Wire (Season 4) \u2014 the institution eating its children, systemic causation without villains",
"Deadwood \u2014 language as character, civilization forming, violence as the grammar of frontier law",
"The Americans \u2014 identity as performance to dissolution, marriage and ideology braided",
"Carniv\u00e0le \u2014 the Depression as mythological space, good and evil as human, slow revelation",
"Babylon Berlin \u2014 Weimar decadence and oncoming darkness, conspiracy in historical texture",
"Black Sails \u2014 the prequel as tragedy, the pirate as proto-revolutionary",
"Rectify \u2014 the man released from prison who cannot be, time lost, trauma without resolution",
"Stalker \u2014 the zone as spiritual test, what you truly want is dangerous",
"Pan\u2019s Labyrinth \u2014 fantasy as psychological survival, the real world more monstrous than the mythic",
"Under the Skin \u2014 the alien observing humanity, predation and then empathy",
"Twin Peaks: The Return \u2014 the return as impossible, time as damage",
"True Detective S1 \u2014 philosophical nihilism as character, Southern Gothic updated",
"The Leftovers \u2014 grief without resolution, the absence as the presence, secular grief as theology",
"Station Eleven \u2014 what is worth preserving after collapse, the traveling theater as civilization\u2019s argument"
],

voice: [
"Close first-person, reliable \u2014 intimacy and limitation simultaneously",
"Close first-person, unreliable \u2014 the gap between what they say and what is true IS the story",
"First-person, retrospective \u2014 we sense the ending\u2019s shadow from the first page",
"First-person present tense \u2014 immediacy, the narrator doesn\u2019t know what happens next",
"Close third-person, single POV \u2014 the camera behind one character\u2019s eyes",
"Close third-person, multiple POV \u2014 reality shifts with the perceiver",
"Omniscient third-person, distant \u2014 godlike, ironic, or tragic",
"Omniscient with intimate intrusion \u2014 wide-angle then suddenly unbearably close",
"Second person \u2014 the reader is implicated, complicity or immersion",
"Epistolary \u2014 letters, journal entries, reports, transcripts, what\u2019s not there matters",
"Found document / archive \u2014 a case file, evidence dossier, fragments assembled",
"Oral / spoken voice \u2014 someone is telling this story out loud, with cadence and withholding",
"Frame narrative \u2014 a story within a story, the distance is the point",
"Collective / community \u201cwe\u201d \u2014 the individual emerges from the communal",
"Rotating unreliable voices \u2014 multiple narrators, the reader triangulates toward truth",
"The child narrator \u2014 precision of detail and incomprehension of meaning",
"The naive or innocent narrator \u2014 horror in the gap between their account and reality",
"Non-human or posthuman POV \u2014 AI, animal, alien, a different relationship to consciousness",
"Fragmented / non-linear \u2014 time out of order, the reader assembles the sequence",
"The metafictional narrator \u2014 knows they are in a story and has opinions about it"
]

};

// Roll a random entry from a table array
window.rollTable = function(table) {
    return table[Math.floor(Math.random() * table.length)];
};

// Compose a random narrative brief from multiple table rolls
window.randomizeNarrativeBrief = function() {
    var T = window.STORY_TABLES;
    var genre = rollTable(T.genreTone);
    var setting = rollTable(T.setting);
    var protag = rollTable(T.protagonist);
    var want = rollTable(T.want);
    var antag = rollTable(T.antagonist);
    var theme = rollTable(T.theme);
    var tone = rollTable(T.touchstone);
    var pov = rollTable(T.voice);

    var brief = genre + '. ' + setting + '. '
        + protag + '. They want ' + want.charAt(0).toLowerCase() + want.slice(1) + '. '
        + 'Antagonist: ' + antag + '. '
        + 'Central question: ' + theme + ' '
        + 'Narrative voice: ' + pov + '. '
        + 'Tonal touchstone: ' + tone + '.';

    document.getElementById('progNarrativeBrief').value = brief;
};
