(function(){
  /* ─── Anti-Trope Defense ─────────────────────────────────────────
     Ban list + randomized genre pool. When the user leaves creative
     direction blank, we actively steer the LLM away from default
     tropes and toward genuinely unusual territory.
     ─────────────────────────────────────────────────────────────── */
  var BANNED_TROPES = [
    'gladiator arena or Roman colosseum settings',
    'space marine or military sci-fi',
    'post-apocalyptic survival',
    'chosen one or prophecy fulfillment',
    'zombie outbreak',
    'generic medieval fantasy (dragon slaying, dungeon crawling)',
    'superhero origin story'
  ];

  var GENRE_POOL = [
    'Corporate Accounting Horror — an audit trail that audits you back',
    'Competitive Birdwatching Noir — binoculars, betrayal, and rare sightings',
    'Municipal Zoning Board Cosmic Horror — the variance was never approved',
    'Insurance Fraud Romance — two adjusters, one suspicious claim',
    'Deep-Sea Botanical Survey — cataloguing organisms that shouldn\'t photosynthesize',
    'Antarctic Radio Station Mystery — the signal predates the station',
    'Venetian Glassblowing Espionage — secrets encoded in crystal',
    '1970s Brutalist Architecture Thriller — the building is watching',
    'Lost Pet Investigation told through flyers and hand-drawn maps',
    'HOA Meeting Minutes That Get Increasingly Disturbing',
    'Recipe Collection Hiding a Conspiracy — the ingredients don\'t exist',
    'Veterinary Clinic Case Files Gone Wrong — the animals remember',
    'Sumerian Tax Collector\'s Diary — debts older than writing',
    'Byzantine Bureaucratic Intrigue — forms within forms within forms',
    'Victorian Sewer Cartography — mapping what lives below',
    'Cold War Library Science — banned books as dead drops',
    'Competitive Origami Underground — folding is a blood sport',
    'Elevator Inspector\'s Existential Crisis — between floors, between worlds',
    'Weather Station at the Edge of Reality — the forecast is always wrong',
    'Lighthouse Keeper\'s Union Dispute — the light must not go out',
    'Plague Doctor\'s Apprentice Journal — the cure is the disease',
    'Archaeological Dig Site Procedural — every layer is a lie',
    'Train Conductor\'s Logbook on a Route That Shouldn\'t Exist',
    'Beekeeping Cooperative Thriller — the hive has a plan',
    'Cartographer of Impossible Coastlines — the shore moves at night',
    'Deep Space Janitor\'s Maintenance Log — someone has to clean up after first contact',
    'Monastery Brewery Conspiracy — the recipe is a prayer is a weapon',
    'Professional Cheese Cave Inspector — aging reveals terrible truths',
    'Retired Circus Performer\'s Memoir — the tent is still standing somewhere'
  ];

  function shufflePick(arr, n) {
    var copy = arr.slice();
    for (var i = copy.length - 1; i > 0; i--) {
      var j = Math.floor(Math.random() * (i + 1));
      var tmp = copy[i]; copy[i] = copy[j]; copy[j] = tmp;
    }
    return copy.slice(0, n);
  }

  /* ─── Schema Specification ─────────────────────────────────────────
     Distilled from liftrpg-schema.json v1.3. This is what the LLM
     reads to understand the JSON structure it must produce.
     ─────────────────────────────────────────────────────────────── */
  var SCHEMA_SPEC = [
    '# LiftRPG Booklet Schema v1.3 — Generation Reference',
    '',
    'You are generating a complete LiftRPG booklet as a single JSON object.',
    'The booklet is a workout journal fused with a branching narrative TTRPG,',
    'designed to be printed as a saddle-stitched half-letter zine and written',
    'in with a pencil during real gym sessions.',
    '',
    '## Top-Level Structure',
    '',
    'The JSON has these top-level keys (all required):',
    '- `meta` — Block-level constants set once, consumed everywhere',
    '- `weeks` — Array of week objects (one per training week)',
    '- `fragments` — Array of found documents (back-of-book, non-sequential)',
    '- `cover` — Title page fields',
    '- `rulesSpread` — How-to-play briefing + password record page',
    '- `endings` — Encrypted ending content (1-3 variants)',
    '',
    '## meta (object)',
    '',
    'Required fields:',
    '- `schemaVersion` (string): Always "1.3.0"',
    '- `generatedAt` (string): ISO 8601 datetime',
    '- `blockTitle` (string): The full title of this story. Rendered in Playfair Display Italic on cover. Example: "The Cartographer of Unmapped Rooms"',
    '- `blockSubtitle` (string): One line beneath title in Share Tech Mono. Feels like an official designation, not a tagline.',
    '- `worldContract` (string): One sentence. The fundamental nature of this world and what it asks of the person inside it. This is the north star for EVERY design and story decision. Write this FIRST.',
    '- `narrativeVoice` (object):',
    '  - `person` ("first"|"second"|"third"): Grammatical person for session card prompts',
    '  - `tense` ("present"|"past"): Tense for session card prompts',
    '  - `narratorStance` (string): One sentence. Who is speaking, to whom, under what conditions.',
    '  - `voiceRationale` (string): Why this voice serves this world contract. Must reference worldContract.',
    '- `literaryRegister` (object):',
    '  - `name` (string): Internal reference name (never printed)',
    '  - `behaviorDescription` (string): What this register does — properties and behaviors, never source names. 3-5 sentences.',
    '  - `forbiddenMoves` (string[]): At least 3 specific prohibitions.',
    '  - `typographicBehavior` (string): How typography participates in this register.',
    '- `weeklyComponentType` (string): The single component type used across all non-boss weeks. Must feel native to the world — a surveyor uses coordinates, an interrogation uses case numbers. Examples: "letter", "coordinate-fragment", "date-fragment"',
    '- `structuralShape` (object):',
    '  - `resolution` ("resolves"|"refuses"|"partial")',
    '  - `temporalOrder` ("forward"|"backward"|"middle-outward"|"fragmented")',
    '  - `narratorReliability` ("reliable"|"unreliable"|"unknown"|"multiple")',
    '  - `promptFragmentRelationship` ("parallel"|"fragments-deepen"|"fragments-contradict"|"prompts-are-the-lie"|"fragments-are-the-lie")',
    '  - `shapeRationale` (string): Why this shape serves this world contract.',
    '- `passwordPlaintext` (string): 4-12 uppercase alphanumeric chars. A real word meaningful within the world. Produced by the boss convergence mechanism applied to all prior weekly components. Pattern: /^[A-Z0-9]{4,12}$/',
    '- `passwordEncryptedEnding` (string): AES-256-GCM encrypted blob of the endings array, keyed on passwordPlaintext. Base64url encoded. Generate the endings first, then encrypt.',
    '- `liftoScript` (string): The raw workout programme pasted by the user. Store verbatim.',
    '- `weekCount` (integer, 4-16): Number of training weeks. Derived from the workout programme.',
    '- `totalSessions` (integer): Total sessions across all weeks.',
    '',
    '## weeks (array of objects)',
    '',
    'One object per week. Length must equal meta.weekCount.',
    '',
    'Each week requires:',
    '- `weekNumber` (integer): 1-indexed',
    '- `title` (string): Feels like a chapter title in the world. Example: "Survey Sector 4 · The Rooms That Close"',
    '- `epigraph` (object): { text, attribution } — A fragment of found text beneath the week title. Attribution is an in-world designation, never a real author.',
    '- `isBossWeek` (boolean): True for the FINAL week only. Replaces fieldOps with bossEncounter.',
    '- `weeklyComponent` (object): { type, value, extractionInstruction } — The component this week contributes. type matches meta.weeklyComponentType. value is the actual component (null on boss week). extractionInstruction is an in-world procedure for recording the component.',
    '- `sessions` (array, 3-6 items): Each session has:',
    '  - `sessionNumber` (integer): 1-indexed within week',
    '  - `label` (string): Example: "Session 2 · Workout B"',
    '  - `exercises` (array): From the workout programme — { name, sets, repsPerSet, weightField, notes }',
    '  - `storyPrompt` (string): 2-4 sentences. Advances the story. Creates a thread the reader follows. Never summarizes.',
    '  - `fragmentRef` (string, optional): Pattern "F.N". Points to a fragment. Only when the prompt creates a thread a specific fragment resolves.',
    '  - `binaryChoice` (object, optional): Present on EXACTLY one session per block at the midpoint week. Two genuine narrative continuations with map-marker circles. { choiceLabel, promptA, promptB }',
    '- `fieldOps` (object, required on non-boss weeks):',
    '  - `mapState` (object): The survey grid — { gridDimensions: {columns: 5-12, rows: 4-8}, tiles: [{col, row, type, label?, annotation?}], currentPosition: {col, row}, floorLabel, mapNote? }. Tile types: "empty"|"cleared"|"locked"|"anomaly"|"current"|"inaccessible".',
    '  - `cipher` (object): The puzzle yielding the weekly component — { type, title, body: {displayText, key?, workSpace: {rows, style}}, noticeabilityDesign, extractionInstruction, characterDerivationProof }. Cipher types: "substitution"|"grid-filter"|"coordinate-lookup"|"index-extraction"|"prime-filter"|"reverse-alphabet"|"ascii-offset"|"fragment-cross-reference"|"map-derived"|"custom".',
    '  - `oracleTable` (object): { title, instruction, mode, entries[] }. mode "simple" = 11 entries (2d6, rolls 2-12). mode "full" = 10 entries (d10xd10, ranges 01-10 through 91-00). Entry types: "fragment" (with fragmentRef) or "consequence" (in-place action).',
    '- `bossEncounter` (object, required when isBossWeek is true):',
    '  - `title` (string): In-world title for the boss page. Not "Final Puzzle".',
    '  - `narrative` (string): 2-4 sentences. The climax story moment.',
    '  - `mechanismDescription` (string): In-world fiction-first instructions for the boss puzzle. Must require all prior components. Completable with booklet + pencil.',
    '  - `componentInputs` (string[]): Ordered list of prior weeks\' component values.',
    '  - `convergenceProof` (string): Step-by-step walkthrough proving full convergence produces passwordPlaintext. Must document 0-1 component, 2-3 component, and 4-5 component states.',
    '  - `passwordRevealInstruction` (string): The final in-world instruction. Ends with "Enter it at liftrpg.co."',
    '  - `binaryChoiceAcknowledgement` (object, optional): { ifA, ifB } — boss page acknowledges binary choice.',
    '- `overflow` (boolean): True when sessions.length > 3. Triggers Part 2 spread.',
    '- `isDeload` (boolean): True for deload weeks. Tonal flag — "deload" never appears in booklet.',
    '- `overflowDocument` (foundDocument, required when overflow is true): Found document for the Part 2 right page.',
    '- `interlude` (object, optional): Typographic interlude page. Must have explicit reason referencing worldContract or literaryRegister.',
    '',
    '## fragments (array of foundDocument, 8-30 items)',
    '',
    'Back-of-book found documents. Non-sequential, mixed types. Each is a distinct document artifact.',
    '',
    'foundDocument structure:',
    '- `id` (string): Pattern "F.N" — e.g., "F.1", "F.14"',
    '- `documentType` ("memo"|"fieldNote"|"transcript"|"inspection"|"correspondence"|"anomaly")',
    '- `inWorldAuthor` (string): Who wrote this within the world. Must be specific.',
    '- `inWorldRecipient` (string): Who it was for.',
    '- `inWorldPurpose` (string): Why this document exists in the world — independent of story function.',
    '- `content` (string): Full text including headers, form fields, redactions [██████], annotations {in braces}.',
    '- `designSpec` (object): { paperTone ("warm"|"neutral"|"cold"|"aged"), primaryTypeface ("mono"|"serif"|"mixed"), headerStyle ("form"|"letterhead"|"handwritten"|"none"), hasRedactions (bool), hasAnnotations (bool) }',
    '- `authenticityChecks` (object): { hasIrrelevantDetail (must be true), couldExistInDifferentStory (must be false), redactionDoesNarrativeWork (true if redactions present, null if not) }',
    '',
    '## cover (object)',
    '',
    '- `title` (string): Same as meta.blockTitle',
    '- `designation` (string): Official-sounding designation. Example: "MSA Survey Log · Block 01 · Restricted Distribution"',
    '- `tagline` (string): One line. Official warning or procedural note — not marketing.',
    '- `colophonLines` (string[], 3-6): Small print: date, schema version, URL. Plus one LLM-written world line.',
    '',
    '## rulesSpread (object)',
    '',
    '- `leftPage` (object):',
    '  - `title` (string): In-world title — not "How to Play". Example: "Personnel Orientation · Survey Conduct & Incident Protocol"',
    '  - `reEntryRule` (object): { progressionType ("lp"|"dp"|"sum"|"custom"), ruleText (string — in-world field procedure for missed weeks) }',
    '  - `sections` (array, 4-6): Each { heading, body }. Cover: using the log, fragments, cipher system, oracle table, password record, liftrpg.co.',
    '- `rightPage` (object): RENDERER-GENERATED from week count. Schema needs: { title, instruction, unlockUrl: "liftrpg.co" }',
    '',
    '## endings (array, 1-3 items)',
    '',
    'Encrypted and stored in meta.passwordEncryptedEnding. Each:',
    '- `variant` (string): What determines which ending shows.',
    '- `content` (object): { documentType, body (full ending text), finalLine (the last line — designed as discrete unit) }',
    '- `designSpec` (string): How the ending page feels to arrive at.'
  ].join('\n');

  /* ─── Generation Instructions ──────────────────────────────────── */
  var INSTRUCTIONS = [
    '# Generation Instructions',
    '',
    '## Output Format',
    '- Return ONLY valid JSON. No markdown code fences. No commentary.',
    '- The JSON must parse successfully with JSON.parse().',
    '- All string values must use proper JSON escaping (newlines as \\n, quotes as \\").',
    '',
    '## World Contract First',
    '- Write meta.worldContract BEFORE generating any other content.',
    '- Every design decision — naming, voice, cipher themes, document types, map labels — must trace back to the world contract.',
    '- If a decision cannot justify itself through the world contract, cut it.',
    '',
    '## Diegetic Everything',
    '- Every label, title, and instruction must feel like it belongs inside the fiction.',
    '- No game terminology: not "puzzle", "level", "boss fight", "checkpoint".',
    '- The booklet is a found document. The workout log is a real institutional form.',
    '',
    '## Found Document Quality',
    '- Every fragment must pass: hasIrrelevantDetail = true, couldExistInDifferentStory = false.',
    '- Use all 6 document types across fragments. Vary paperTone and typeface.',
    '- Redactions must do narrative work or don\'t use them.',
    '',
    '## Cipher Design',
    '- Week 1 cipher: solvable in under 60 seconds.',
    '- Difficulty escalates but with variance (not monotonic).',
    '- noticeabilityDesign is REQUIRED — an unwarned reader must discover the puzzle exists.',
    '- characterDerivationProof must verify that solving the cipher produces exactly weeklyComponent.value.',
    '',
    '## Password & Encryption',
    '- passwordPlaintext: a meaningful word in the world, 4-12 chars, uppercase alphanumeric only.',
    '- The boss convergenceProof must demonstrate that applying the mechanism to all componentInputs produces passwordPlaintext exactly.',
    '- Generate endings content, then encrypt with AES-256-GCM keyed on passwordPlaintext, store as base64url in passwordEncryptedEnding.',
    '',
    '## Story Prompts',
    '- 2-4 sentences per session. Present tense (or as established by narrativeVoice).',
    '- Each must advance the story. Never summarize. Create threads the reader follows.',
    '- End sessions with unresolved tension (Zeigarnik Effect).',
    '',
    '## Structural Rules',
    '- Exactly one binaryChoice per block, at the midpoint week, never on boss week.',
    '- Exactly one week has isBossWeek: true (the final week).',
    '- Boss week weeklyComponent.value is null.',
    '- Fragment IDs ("F.1", "F.2", ...) must be unique and referenced consistently by fragmentRef pointers.',
    '- Oracle table: simple mode = 11 entries (2d6), full mode = 10 entries (d10xd10).',
    '- Maximum 3 consequence-type oracle entries per week.',
    '',
    '## Exercise Data',
    '- Copy exercise data EXACTLY from the workout programme provided below.',
    '- Do not rename, reorder, or modify exercises.',
    '- sets, repsPerSet, weightField, and notes come directly from the programme.'
  ].join('\n');

  /* ─── Public API ───────────────────────────────────────────────── */
  window.generatePrompt = function(workout, brief, dice){
    var parts = [
      SCHEMA_SPEC,
      '',
      '---',
      '',
      '# Your Inputs',
      '',
      '## Workout Programme',
      '',
      workout,
      '',
      '## Creative Direction',
      '',
      brief || (function(){
        var picks = shufflePick(GENRE_POOL, 4);
        return [
          'No specific creative direction provided.',
          '',
          'DO NOT default to these overused genres: ' + BANNED_TROPES.join('; ') + '.',
          'These are the most common LLM defaults and produce identical-feeling booklets.',
          '',
          'Instead, consider one of these unusual directions (or invent something equally unexpected):',
          '- ' + picks[0],
          '- ' + picks[1],
          '- ' + picks[2],
          '- ' + picks[3],
          '',
          'The world contract should feel genuinely surprising. Use the workout programme\'s',
          'structure (heavy weeks, deload weeks, exercise selection) to inspire the fiction\'s texture.'
        ].join('\n');
      })(),
      '',
      '## Dice Selection',
      '',
      dice,
      'Tip: Google "roll ' + dice + '" — works as dice if you have none.',
      '',
      '---',
      '',
      INSTRUCTIONS
    ];
    return parts.join('\n');
  };
})();
