/**
 * form-metrics/index.mjs — THE EMITTED STYLESHEET'S ONE HOME
 *
 * Every atom family with a form set owns its geometry in its own module beside
 * this one, and each of those modules emits its own SECTION of the stylesheet.
 * This file owns the three things that belong to the FILE rather than to any
 * family: where it lives, what its banner says, and the order the sections are
 * written in.
 *
 * Why a separate module rather than "the first family emits the file": three
 * families each emitting a whole stylesheet would be three stylesheets, and the
 * one that happened to be imported by the emitter would win. The renderer links
 * ONE file (`public/renderer/index.html`), the validator byte-diffs ONE file,
 * and `scripts/check-form-variants.mjs` asserts both halves of that — so there
 * is one emitter, here.
 *
 * DETERMINISM (gen-reference.mjs's law): a pure function of the constants in
 * the family modules. No date, no hash, no iteration order — the sections are
 * written in the order ATOM_FORM_FAMILIES declares them, which is the same
 * order the die, the floor, the schema and the gate walk.
 */

import { ATOM_FORM_FAMILIES } from '../../../contracts/contract-constants.mjs';
import {
  emitSessionCardFormCss,
  FORM_ROOT_SELECTOR as SESSION_CARD_ROOT
} from './session-card-forms.mjs';
import {
  emitOracleTableFormCss,
  FORM_ROOT_SELECTOR as ORACLE_TABLE_ROOT
} from './oracle-table-forms.mjs';
import {
  emitFragmentDocFormCss,
  FORM_ROOT_SELECTOR as FRAGMENT_DOC_ROOT
} from './fragment-doc-forms.mjs';
import {
  emitLedgerSpreadFormCss,
  FORM_ROOT_SELECTOR as LEDGER_SPREAD_ROOT
} from './ledger-spread-forms.mjs';

/**
 * Where the emitted stylesheet lives, repo-relative. Declared here so the
 * emitter, the gate and the `<link>` audit all name one string.
 */
export const FORM_VARIANTS_CSS_PATH = 'public/renderer/form-variants.css';

/**
 * family id → its section emitter. Keyed by the contract's own family ids so a
 * family declared in ATOM_FORM_FAMILIES with no geometry module fails LOUDLY
 * here (a missing section is a form that resolves, stamps its attribute and
 * draws nothing — Hollow Success, and the gate's named enemy) rather than
 * emitting a stylesheet that is quietly short one family.
 */
const SECTION_EMITTERS = {
  sessionCard: emitSessionCardFormCss,
  oracleTable: emitOracleTableFormCss,
  fragmentDoc: emitFragmentDocFormCss,
  ledgerSpread: emitLedgerSpreadFormCss
};

/**
 * family id → the selector root its rules hang off. The atom TYPE and the class
 * it renders as are not always the same word (`oracle-table` renders as
 * `.oracle-zone`), so an asset check that derived the selector from the type
 * would look for rules that were never supposed to exist and pass on a family
 * that emitted nothing.
 */
export const FORM_ROOT_SELECTORS = {
  sessionCard: SESSION_CARD_ROOT,
  oracleTable: ORACLE_TABLE_ROOT,
  fragmentDoc: FRAGMENT_DOC_ROOT,
  ledgerSpread: LEDGER_SPREAD_ROOT
};

const GENERATED_BANNER =
  '/* GENERATED by scripts/gen-reference.mjs from\n'
  + ' * public/renderer/modules/form-metrics/*.mjs — DO NOT EDIT.\n'
  + ' * Regenerate: npm run gen:reference   (npm run validate byte-diffs this file)\n'
  + ' *\n'
  + ' * THE VARIANT CONTRACT (docs/craft/ARRANGEMENT.md §3): every number here is\n'
  + ' * interpolated from a constant the matching atom\'s estimate imports, so the\n'
  + ' * stylesheet and the arithmetic cannot disagree. Editing this file by hand\n'
  + ' * breaks the byte-diff; editing it and re-running the emitter reverts you.\n'
  + ' */';

/**
 * The complete `public/renderer/form-variants.css`.
 *
 * @returns {string}
 */
export function emitFormVariantsCss() {
  const parts = [GENERATED_BANNER, ''];
  ATOM_FORM_FAMILIES.forEach((family) => {
    const emit = SECTION_EMITTERS[family.id];
    if (typeof emit !== 'function') {
      throw new Error(`form-metrics: ATOM_FORM_FAMILIES declares "${family.id}" but no geometry `
        + 'module emits its CSS — a form that resolves and draws nothing is Hollow Success. '
        + 'Add public/renderer/modules/form-metrics/<family>-forms.mjs and register it here.');
    }
    parts.push(emit(), '');
  });
  return parts.join('\n');
}
