import { alpha, mergeObjects } from './utils.js?v=43';

const THEME_PRESETS = {
  pastoral: {
    '--font-display': '"Playfair Display", Georgia, serif',
    '--font-body': '"Libre Baskerville", Georgia, serif',
    '--font-mono': '"Share Tech Mono", monospace',
    '--font-accent': '"Share Tech Mono", monospace',
    '--weight-body': '400',
    '--weight-heading': '700',
    '--weight-label': '400',
    '--weight-emphasis': '700',
    '--page-ink': '#181714',
    '--page-paper': '#f1ebe0',
    '--page-secondary-paper': '#efe5d7',
    '--page-accent': '#8b2a2a',
    '--page-muted': '#857d72',
    '--page-rule': '#ccc5b6',
    '--page-fog': '#ddd6c5',
    '--page-surface': '#f1ebe0',
    '--page-underlay': 'linear-gradient(180deg, rgba(255,255,255,.045) 0%, rgba(0,0,0,.012) 100%)',
    '--panel-surface': 'rgba(246,241,231,0.82)',
    '--panel-secondary-surface': 'rgba(235,228,212,0.42)',
    '--card-surface': 'rgba(244,239,228,0.72)',
    '--line-style': 'solid',
    '--line-width-hair': '1px',
    '--line-width-rule': '1.2px',
    '--line-width-frame': '1.5px',
    '--surface-radius': '3px',
    '--surface-shadow': '0 6px 14px rgba(0,0,0,0.025)',
    '--page-shadow': '0 18px 30px rgba(0,0,0,0.12)',
    '--noise-opacity': '0.055',
    '--fog-opacity': '0.1',
    '--rule-opacity': '0.75',
    '--stamp-opacity': '0.85',
    '--label-size': '6.3pt',
    '--label-spacing': '0.28em',
    '--label-transform': 'uppercase',
    '--heading-style': 'italic',
    '--heading-size-xl': '32pt',
    '--heading-size-lg': '16pt',
    '--heading-size-md': '11pt',
    '--body-size': '8.4pt',
    '--body-line-height': '1.58',
    '--small-size': '6.2pt',
    '--mono-size': '6.4pt',
    '--grid-stroke-style': 'solid',
    '--grid-dot-opacity': '0.24',
    '--grid-fill': 'rgba(204,197,182,0.28)',
    '--track-fill': 'rgba(221,214,197,0.38)',
    '--badge-style': 'normal',
    '--callout-surface': 'rgba(241,235,224,0.28)',
    '--highlight-surface': 'rgba(139,42,42,0.07)',
    '--page-margin': '0.3in',
    '--page-live-top': '0.3in',
    '--page-live-right': '0.3in',
    '--page-live-bottom': '0.28in',
    '--page-live-left': '0.3in'
  },
  government: {
    '--font-display': '"Playfair Display", Georgia, serif',
    '--font-body': '"IBM Plex Mono", "Courier New", Courier, monospace',
    '--font-mono': '"IBM Plex Mono", "Courier New", Courier, monospace',
    '--font-accent': '"Share Tech Mono", monospace',
    '--weight-body': '400',
    '--weight-heading': '700',
    '--weight-label': '600',
    '--weight-emphasis': '700',
    '--page-ink': '#111111',
    '--page-paper': '#e6dfd1',
    '--page-secondary-paper': '#ded2be',
    '--page-accent': '#a33b3b',
    '--page-muted': '#5e5a51',
    '--page-rule': '#a33b3b',
    '--page-fog': '#dacfbe',
    '--page-surface': 'linear-gradient(180deg, #e6dfd1 0%, #dacfbe 100%)',
    '--page-underlay': 'none',
    '--panel-surface': 'linear-gradient(180deg, rgba(230, 223, 209, 0.98) 0%, rgba(218, 207, 190, 0.92) 100%)',
    '--panel-secondary-surface': 'transparent',
    '--card-surface': 'transparent',
    '--line-style': 'solid',
    '--line-width-hair': '1px',
    '--line-width-rule': '1.5px',
    '--line-width-frame': '2px',
    '--surface-radius': '0px',
    '--surface-shadow': '0 18px 34px rgba(0, 0, 0, 0.08)',
    '--page-shadow': '0 24px 56px rgba(0, 0, 0, 0.20)',
    '--noise-opacity': '0.12',
    '--fog-opacity': '0.1',
    '--rule-opacity': '0.8',
    '--stamp-opacity': '0.9',
    '--label-size': '6pt',
    '--label-spacing': '0.28em',
    '--label-transform': 'uppercase',
    '--heading-style': 'italic',
    '--heading-size-xl': '38pt',
    '--heading-size-lg': '16pt',
    '--heading-size-md': '12pt',
    '--body-size': '9pt',
    '--body-line-height': '1.5',
    '--small-size': '6.2pt',
    '--mono-size': '6.4pt',
    '--grid-stroke-style': 'solid',
    '--grid-dot-opacity': '0.5',
    '--grid-fill': 'rgba(163, 59, 59, 0.08)',
    '--track-fill': 'rgba(218, 207, 190, 0.4)',
    '--badge-style': 'normal',
    '--callout-surface': 'rgba(218, 207, 190, 0.22)',
    '--highlight-surface': 'rgba(163, 59, 59, 0.12)',
    '--page-margin': '0.4in'
  },
  cyberpunk: {
    '--font-display': '"Share Tech Mono", monospace',
    '--font-body': '"IBM Plex Mono", monospace',
    '--font-mono': '"IBM Plex Mono", monospace',
    '--font-accent': '"Share Tech Mono", monospace',
    '--weight-body': '400',
    '--weight-heading': '600',
    '--weight-label': '600',
    '--weight-emphasis': '700',
    '--page-ink': '#00ffcc',
    '--page-paper': '#0a0a0a',
    '--page-accent': '#ff00ff',
    '--page-muted': '#008866',
    '--page-rule': '#00ffcc',
    '--page-fog': '#111111',
    '--page-surface': 'linear-gradient(180deg, #0a0a0a 0%, #111111 100%)',
    '--page-underlay': 'repeating-linear-gradient(180deg, rgba(0,255,204,0.06) 0 2px, transparent 2px 4px)',
    '--panel-surface': 'linear-gradient(180deg, rgba(10,10,10,0.95) 0%, rgba(17,17,17,0.92) 100%)',
    '--panel-secondary-surface': 'linear-gradient(180deg, rgba(0,255,204,0.1) 0%, transparent 100%)',
    '--card-surface': 'rgba(17,17,17,0.8)',
    '--line-style': 'solid',
    '--line-width-hair': '1px',
    '--line-width-rule': '1px',
    '--line-width-frame': '2px',
    '--surface-radius': '0px',
    '--surface-shadow': '0 0px 20px rgba(0, 255, 204, 0.2)',
    '--page-shadow': '0 24px 50px rgba(0,0,0,0.6)',
    '--noise-opacity': '0.2',
    '--fog-opacity': '0.3',
    '--rule-opacity': '1',
    '--stamp-opacity': '1',
    '--label-size': '7pt',
    '--label-spacing': '0.2em',
    '--label-transform': 'uppercase',
    '--heading-style': 'normal',
    '--heading-size-xl': '24pt',
    '--heading-size-lg': '14pt',
    '--heading-size-md': '10pt',
    '--body-size': '8pt',
    '--body-line-height': '1.4',
    '--small-size': '6pt',
    '--mono-size': '8pt',
    '--grid-stroke-style': 'dotted',
    '--grid-dot-opacity': '0.5',
    '--grid-fill': 'rgba(0, 255, 204, 0.1)',
    '--track-fill': 'rgba(0, 255, 204, 0.2)',
    '--badge-style': 'normal',
    '--callout-surface': 'rgba(255, 0, 255, 0.1)',
    '--highlight-surface': 'rgba(0, 255, 204, 0.15)',
    '--page-margin': '0.3in'
  },
  scifi: {
    '--font-display': 'system-ui, -apple-system, sans-serif',
    '--font-body': 'system-ui, -apple-system, sans-serif',
    '--font-mono': '"IBM Plex Mono", monospace',
    '--font-accent': 'system-ui, -apple-system, sans-serif',
    '--weight-body': '400',
    '--weight-heading': '600',
    '--weight-label': '500',
    '--weight-emphasis': '700',
    '--page-ink': '#222222',
    '--page-paper': '#ffffff',
    '--page-accent': '#0066ff',
    '--page-muted': '#888888',
    '--page-rule': '#e0e0e0',
    '--page-fog': '#f5f7fa',
    '--page-surface': 'linear-gradient(180deg, #ffffff 0%, #f5f7fa 100%)',
    '--page-underlay': 'none',
    '--panel-surface': 'linear-gradient(180deg, rgba(255,255,255,0.98) 0%, rgba(245,247,250,0.92) 100%)',
    '--panel-secondary-surface': 'rgba(245,247,250,0.8)',
    '--card-surface': 'rgba(255,255,255,1)',
    '--line-style': 'solid',
    '--line-width-hair': '1px',
    '--line-width-rule': '1px',
    '--line-width-frame': '1.5px',
    '--surface-radius': '4px',
    '--surface-shadow': '0 8px 24px rgba(0, 102, 255, 0.08)',
    '--page-shadow': '0 24px 40px rgba(0,0,0,0.1)',
    '--noise-opacity': '0.02',
    '--fog-opacity': '0.05',
    '--rule-opacity': '1',
    '--stamp-opacity': '0.9',
    '--label-size': '6.5pt',
    '--label-spacing': '0.15em',
    '--label-transform': 'uppercase',
    '--heading-style': 'normal',
    '--heading-size-xl': '28pt',
    '--heading-size-lg': '16pt',
    '--heading-size-md': '11pt',
    '--body-size': '8.5pt',
    '--body-line-height': '1.6',
    '--small-size': '6.5pt',
    '--mono-size': '7.5pt',
    '--grid-stroke-style': 'solid',
    '--grid-dot-opacity': '0.2',
    '--grid-fill': 'rgba(0, 102, 255, 0.04)',
    '--track-fill': 'rgba(224, 224, 224, 0.4)',
    '--badge-style': 'normal',
    '--callout-surface': 'rgba(0, 102, 255, 0.06)',
    '--highlight-surface': 'rgba(0, 102, 255, 0.1)',
    '--page-margin': '0.45in'
  },
  fantasy: {
    '--font-display': '"Playfair Display", serif',
    '--font-body': '"Libre Baskerville", serif',
    '--font-mono': '"Libre Baskerville", serif',
    '--font-accent': '"Playfair Display", serif',
    '--weight-body': '400',
    '--weight-heading': '700',
    '--weight-label': '600',
    '--weight-emphasis': '700',
    '--page-ink': '#1a3322',
    '--page-paper': '#f4ecc2',
    '--page-accent': '#c5a059',
    '--page-muted': '#5c6b5d',
    '--page-rule': '#c5a059',
    '--page-fog': '#eaddad',
    '--page-surface': 'linear-gradient(180deg, #f4ecc2 0%, #eaddad 100%)',
    '--page-underlay': 'none',
    '--panel-surface': 'linear-gradient(180deg, rgba(244,236,194,0.98) 0%, rgba(234,221,173,0.92) 100%)',
    '--panel-secondary-surface': 'transparent',
    '--card-surface': 'transparent',
    '--line-style': 'solid',
    '--line-width-hair': '1px',
    '--line-width-rule': '1.5px',
    '--line-width-frame': '2.5px',
    '--surface-radius': '0px',
    '--surface-shadow': '0 18px 34px rgba(26, 51, 34, 0.15)',
    '--page-shadow': '0 24px 56px rgba(0, 0, 0, 0.25)',
    '--noise-opacity': '0.15',
    '--fog-opacity': '0.2',
    '--rule-opacity': '0.8',
    '--stamp-opacity': '0.7',
    '--label-size': '7pt',
    '--label-spacing': '0.15em',
    '--label-transform': 'uppercase',
    '--heading-style': 'italic',
    '--heading-size-xl': '32pt',
    '--heading-size-lg': '16pt',
    '--heading-size-md': '12pt',
    '--body-size': '9pt',
    '--body-line-height': '1.55',
    '--small-size': '6.5pt',
    '--mono-size': '8pt',
    '--grid-stroke-style': 'dotted',
    '--grid-dot-opacity': '0.6',
    '--grid-fill': 'rgba(197, 160, 89, 0.1)',
    '--track-fill': 'rgba(234, 221, 173, 0.5)',
    '--badge-style': 'italic',
    '--callout-surface': 'rgba(197, 160, 89, 0.15)',
    '--highlight-surface': 'rgba(26, 51, 34, 0.1)',
    '--page-margin': '0.36in'
  },
  noir: {
    '--font-display': '"Share Tech Mono", monospace',
    '--font-body': '"IBM Plex Mono", monospace',
    '--font-mono': '"IBM Plex Mono", monospace',
    '--font-accent': '"Share Tech Mono", monospace',
    '--weight-body': '600',
    '--weight-heading': '700',
    '--weight-label': '700',
    '--weight-emphasis': '700',
    '--page-ink': '#000000',
    '--page-paper': '#e4e4e4',
    '--page-accent': '#000000',
    '--page-muted': '#555555',
    '--page-rule': '#000000',
    '--page-fog': '#c8c8c8',
    '--page-surface': 'linear-gradient(180deg, #e4e4e4 0%, #d0d0d0 100%)',
    '--page-underlay': 'none',
    '--panel-surface': 'linear-gradient(180deg, rgba(228,228,228,0.98) 0%, rgba(200,200,200,0.92) 100%)',
    '--panel-secondary-surface': 'rgba(0,0,0,0.05)',
    '--card-surface': 'linear-gradient(180deg, rgba(228,228,228,0.98) 0%, rgba(200,200,200,0.92) 100%)',
    '--line-style': 'solid',
    '--line-width-hair': '1.5px',
    '--line-width-rule': '2.5px',
    '--line-width-frame': '4px',
    '--surface-radius': '0px',
    '--surface-shadow': '0 20px 40px rgba(0,0,0,0.4)',
    '--page-shadow': '0 24px 60px rgba(0,0,0,0.5)',
    '--noise-opacity': '0.25',
    '--fog-opacity': '0.1',
    '--rule-opacity': '1',
    '--stamp-opacity': '0.9',
    '--label-size': '7.5pt',
    '--label-spacing': '0.2em',
    '--label-transform': 'uppercase',
    '--heading-style': 'normal',
    '--heading-size-xl': '26pt',
    '--heading-size-lg': '15pt',
    '--heading-size-md': '11pt',
    '--body-size': '8.5pt',
    '--body-line-height': '1.5',
    '--small-size': '7pt',
    '--mono-size': '8.5pt',
    '--grid-stroke-style': 'solid',
    '--grid-dot-opacity': '0.8',
    '--grid-fill': 'rgba(0,0,0,0.08)',
    '--track-fill': 'rgba(0,0,0,0.15)',
    '--badge-style': 'normal',
    '--callout-surface': 'rgba(0,0,0,0.08)',
    '--highlight-surface': 'rgba(0,0,0,0.15)',
    '--page-margin': '0.35in'
  },
  steampunk: {
    '--font-display': '"Playfair Display", serif',
    '--font-body': '"Libre Baskerville", serif',
    '--font-mono': '"IBM Plex Mono", monospace',
    '--font-accent': '"Share Tech Mono", monospace',
    '--weight-body': '400',
    '--weight-heading': '700',
    '--weight-label': '600',
    '--weight-emphasis': '700',
    '--page-ink': '#3e2f24',
    '--page-paper': '#d9c8b4',
    '--page-accent': '#b87333',
    '--page-muted': '#7a6452',
    '--page-rule': '#b5a642',
    '--page-fog': '#c4b09c',
    '--page-surface': 'linear-gradient(180deg, #d9c8b4 0%, #c4b09c 100%)',
    '--page-underlay': 'none',
    '--panel-surface': 'linear-gradient(180deg, rgba(217,200,180,0.98) 0%, rgba(196,176,156,0.92) 100%)',
    '--panel-secondary-surface': 'rgba(184,115,51,0.08)',
    '--card-surface': 'linear-gradient(180deg, rgba(217,200,180,0.98) 0%, rgba(196,176,156,0.92) 100%)',
    '--line-style': 'double',
    '--line-width-hair': '1px',
    '--line-width-rule': '3px',
    '--line-width-frame': '4px',
    '--surface-radius': '0px',
    '--surface-shadow': '0 18px 34px rgba(62, 47, 36, 0.25)',
    '--page-shadow': '0 24px 50px rgba(0,0,0,0.3)',
    '--noise-opacity': '0.18',
    '--fog-opacity': '0.2',
    '--rule-opacity': '0.9',
    '--stamp-opacity': '0.8',
    '--label-size': '6.5pt',
    '--label-spacing': '0.22em',
    '--label-transform': 'uppercase',
    '--heading-style': 'normal',
    '--heading-size-xl': '28pt',
    '--heading-size-lg': '15pt',
    '--heading-size-md': '11pt',
    '--body-size': '8.5pt',
    '--body-line-height': '1.5',
    '--small-size': '6.2pt',
    '--mono-size': '7.5pt',
    '--grid-stroke-style': 'solid',
    '--grid-dot-opacity': '0.5',
    '--grid-fill': 'rgba(184, 115, 51, 0.1)',
    '--track-fill': 'rgba(181, 166, 66, 0.2)',
    '--badge-style': 'normal',
    '--callout-surface': 'rgba(184, 115, 51, 0.15)',
    '--highlight-surface': 'rgba(181, 166, 66, 0.15)',
    '--page-margin': '0.38in'
  },
  minimalist: {
    '--font-display': 'system-ui, -apple-system, sans-serif',
    '--font-body': 'system-ui, -apple-system, sans-serif',
    '--font-mono': '"IBM Plex Mono", monospace',
    '--font-accent': 'system-ui, -apple-system, sans-serif',
    '--weight-body': '400',
    '--weight-heading': '600',
    '--weight-label': '600',
    '--weight-emphasis': '700',
    '--page-ink': '#000000',
    '--page-paper': '#ffffff',
    '--page-accent': '#000000',
    '--page-muted': '#888888',
    '--page-rule': '#e0e0e0',
    '--page-fog': '#fdfdfd',
    '--page-surface': '#ffffff',
    '--page-underlay': 'none',
    '--panel-surface': '#ffffff',
    '--panel-secondary-surface': '#fcfcfc',
    '--card-surface': '#ffffff',
    '--line-style': 'solid',
    '--line-width-hair': '1px',
    '--line-width-rule': '1px',
    '--line-width-frame': '2px',
    '--surface-radius': '0px',
    '--surface-shadow': 'none',
    '--page-shadow': '0 20px 40px rgba(0,0,0,0.05)',
    '--noise-opacity': '0.01',
    '--fog-opacity': '0',
    '--rule-opacity': '1',
    '--stamp-opacity': '1',
    '--label-size': '6pt',
    '--label-spacing': '0.25em',
    '--label-transform': 'uppercase',
    '--heading-style': 'normal',
    '--heading-size-xl': '30pt',
    '--heading-size-lg': '16pt',
    '--heading-size-md': '11pt',
    '--body-size': '8.5pt',
    '--body-line-height': '1.65',
    '--small-size': '6.5pt',
    '--mono-size': '7.5pt',
    '--grid-stroke-style': 'solid',
    '--grid-dot-opacity': '0.1',
    '--grid-fill': 'rgba(0,0,0,0.02)',
    '--track-fill': 'rgba(0,0,0,0.05)',
    '--badge-style': 'normal',
    '--callout-surface': 'rgba(0,0,0,0.03)',
    '--highlight-surface': 'rgba(0,0,0,0.06)',
    '--page-margin': '0.5in'
  },
  nautical: {
    '--font-display': '"Playfair Display", serif',
    '--font-body': '"Libre Baskerville", serif',
    '--font-mono': '"IBM Plex Mono", monospace',
    '--font-accent': '"Libre Baskerville", serif',
    '--weight-body': '400',
    '--weight-heading': '700',
    '--weight-label': '600',
    '--weight-emphasis': '700',
    '--page-ink': '#001a33',
    '--page-paper': '#f5f5dc',
    '--page-accent': '#8a3324',
    '--page-muted': '#5c6b73',
    '--page-rule': '#334c66',
    '--page-fog': '#e6e6cc',
    '--page-surface': 'linear-gradient(180deg, #f5f5dc 0%, #e6e6cc 100%)',
    '--page-underlay': 'none',
    '--panel-surface': 'linear-gradient(180deg, rgba(245,245,220,0.98) 0%, rgba(230,230,204,0.92) 100%)',
    '--panel-secondary-surface': 'rgba(0,26,51,0.05)',
    '--card-surface': 'transparent',
    '--line-style': 'solid',
    '--line-width-hair': '1px',
    '--line-width-rule': '1.5px',
    '--line-width-frame': '2px',
    '--surface-radius': '0px',
    '--surface-shadow': '0 16px 30px rgba(0, 26, 51, 0.15)',
    '--page-shadow': '0 24px 50px rgba(0,0,0,0.2)',
    '--noise-opacity': '0.1',
    '--fog-opacity': '0.15',
    '--rule-opacity': '0.85',
    '--stamp-opacity': '0.85',
    '--label-size': '6.8pt',
    '--label-spacing': '0.22em',
    '--label-transform': 'uppercase',
    '--heading-style': 'normal',
    '--heading-size-xl': '26pt',
    '--heading-size-lg': '15pt',
    '--heading-size-md': '11pt',
    '--body-size': '8.5pt',
    '--body-line-height': '1.58',
    '--small-size': '6.4pt',
    '--mono-size': '7.2pt',
    '--grid-stroke-style': 'solid',
    '--grid-dot-opacity': '0.4',
    '--grid-fill': 'rgba(138, 51, 36, 0.08)',
    '--track-fill': 'rgba(51, 76, 102, 0.2)',
    '--badge-style': 'normal',
    '--callout-surface': 'rgba(51, 76, 102, 0.1)',
    '--highlight-surface': 'rgba(138, 51, 36, 0.15)',
    '--page-margin': '0.36in'
  },
  occult: {
    '--font-display': '"Playfair Display", serif',
    '--font-body': '"Libre Baskerville", serif',
    '--font-mono': '"Libre Baskerville", serif',
    '--font-accent': '"Playfair Display", serif',
    '--weight-body': '400',
    '--weight-heading': '700',
    '--weight-label': '600',
    '--weight-emphasis': '700',
    '--page-ink': '#2a1a2e',
    '--page-paper': '#c2b28f',
    '--page-accent': '#8c001a',
    '--page-muted': '#5c4a63',
    '--page-rule': '#5a3d4a',
    '--page-fog': '#a69673',
    '--page-surface': 'linear-gradient(180deg, #c2b28f 0%, #a69673 100%)',
    '--page-underlay': 'none',
    '--panel-surface': 'linear-gradient(180deg, rgba(194,178,143,0.98) 0%, rgba(166,150,115,0.92) 100%)',
    '--panel-secondary-surface': 'rgba(140,0,26,0.06)',
    '--card-surface': 'transparent',
    '--line-style': 'solid',
    '--line-width-hair': '1px',
    '--line-width-rule': '1.5px',
    '--line-width-frame': '2.5px',
    '--surface-radius': '0px',
    '--surface-shadow': '0 20px 38px rgba(42, 26, 46, 0.25)',
    '--page-shadow': '0 24px 60px rgba(0,0,0,0.4)',
    '--noise-opacity': '0.22',
    '--fog-opacity': '0.25',
    '--rule-opacity': '0.9',
    '--stamp-opacity': '0.8',
    '--label-size': '6.5pt',
    '--label-spacing': '0.18em',
    '--label-transform': 'uppercase',
    '--heading-style': 'italic',
    '--heading-size-xl': '30pt',
    '--heading-size-lg': '16pt',
    '--heading-size-md': '12pt',
    '--body-size': '9pt',
    '--body-line-height': '1.45',
    '--small-size': '6.4pt',
    '--mono-size': '8pt',
    '--grid-stroke-style': 'dotted',
    '--grid-dot-opacity': '0.7',
    '--grid-fill': 'rgba(140, 0, 26, 0.08)',
    '--track-fill': 'rgba(90, 61, 74, 0.3)',
    '--badge-style': 'italic',
    '--callout-surface': 'rgba(90, 61, 74, 0.15)',
    '--highlight-surface': 'rgba(140, 0, 26, 0.15)',
    '--page-margin': '0.36in'
  }
};

export function resolveTheme(data) {
  const theme = (data && data.theme) || {};
  const archetype = theme.visualArchetype || 'pastoral';
  const preset = THEME_PRESETS[archetype] || THEME_PRESETS.pastoral;
  const palette = theme.palette || {};
  const tokens = mergeObjects(preset, theme.tokens || {});

  if (palette.ink) tokens['--page-ink'] = palette.ink;
  if (palette.paper) tokens['--page-paper'] = palette.paper;
  if (palette.paper && !theme.tokens) tokens['--page-secondary-paper'] = palette.paper;
  if (palette.accent) tokens['--page-accent'] = palette.accent;
  if (palette.muted) tokens['--page-muted'] = palette.muted;
  if (palette.rule) tokens['--page-rule'] = palette.rule;
  if (palette.fog) tokens['--page-fog'] = palette.fog;

  if (palette.paper && !theme.tokens) {
    tokens['--page-surface'] = 'linear-gradient(180deg, ' + palette.paper + ' 0%, ' + alpha(palette.paper, 0.92) + ' 100%)';
    tokens['--panel-surface'] = 'linear-gradient(180deg, ' + alpha(palette.paper, 0.98) + ' 0%, ' + alpha(palette.paper, 0.9) + ' 100%)';
    tokens['--card-surface'] = tokens['--panel-surface'];
  }

  tokens['--page-underlay'] = tokens['--page-underlay'] || 'none';
  tokens['--page-secondary-paper'] = tokens['--page-secondary-paper'] || tokens['--page-paper'];
  tokens['--panel-secondary-surface'] = tokens['--panel-secondary-surface'] || alpha(tokens['--page-fog'], 0.28);
  tokens['--callout-surface'] = tokens['--callout-surface'] || alpha(tokens['--page-fog'], 0.2);
  tokens['--highlight-surface'] = tokens['--highlight-surface'] || alpha(tokens['--page-accent'], 0.12);

  return {
    archetype,
    tokens
  };
}

export function applyTheme(container, theme) {
  container.setAttribute('data-archetype', theme.archetype);
  Object.keys(theme.tokens).forEach((key) => {
    container.style.setProperty(key, theme.tokens[key]);
  });
}
